#!/usr/bin/env tsx
/**
 * Generate the `./bundled` entry — a static-bundler-friendly variant that
 * statically `require`s every per-country JSON file shipped in `data/`.
 *
 * We bypass tsup for this entry because tsup's ESM/CJS interop replaces
 * `require(literal)` with `__require(literal)`, which Metro's static
 * dependency extractor does not follow. Emitting the dist files by hand
 * keeps the literal `require()` calls Metro needs.
 *
 * Outputs (re-run after `build-indexes` and after `tsup`):
 *   src/bundled.ts        for `tsc --noEmit` and as on-disk reference
 *   dist/bundled.cjs      runtime entry (Metro / webpack / Rollup pick this up)
 *   dist/bundled.mjs      ESM bridge that imports from the CJS file via createRequire
 *   dist/bundled.d.ts     ambient declarations
 *   dist/bundled.d.cts    same, for `require`-condition consumers
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import type { Manifest } from '../src/types.js';

const ROOT = new URL('../', import.meta.url);
const MANIFEST_PATH = new URL('data/manifest.json', ROOT);
const SRC_OUT = new URL('src/bundled.ts', ROOT);
const DIST_DIR = new URL('dist/', ROOT);

const HEADER = '// @generated by scripts/build-bundled.ts — DO NOT EDIT.';

async function main() {
  const manifest: Manifest = JSON.parse(await readFile(MANIFEST_PATH, 'utf8'));
  const codes = Object.keys(manifest.countries).sort();
  await mkdir(DIST_DIR, { recursive: true });

  await writeFile(SRC_OUT, renderSource(codes));
  await writeFile(new URL('bundled.cjs', DIST_DIR), renderCjs(codes));
  await writeFile(new URL('bundled.mjs', DIST_DIR), renderMjs());
  await writeFile(new URL('bundled.d.ts', DIST_DIR), renderDts());
  await writeFile(new URL('bundled.d.cts', DIST_DIR), renderDts());

  console.log(`bundled entry written (${codes.length} countries)`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});

// -------- Renderers --------

function renderSource(codes: readonly string[]): string {
  // src/bundled.ts is consumed by `tsc --noEmit` only — not by tsup. We use
  // `declare const require` so TS accepts the CJS-style requires in a package
  // declared as `"type": "module"`.
  const loaders = codes
    .map((cc) => `  ${cc}: () => require('../data/${cc}.json'),`)
    .join('\n');
  return `${HEADER}
// Source: data/manifest.json (${codes.length} countries).

import { isCountryLoaded, registerCountry } from './registry.js';
import {
  validatePostalCode as packageValidate,
  getCountryFormat as packageGetCountryFormat,
} from './validator.js';
import type { CountryData, CountryFormat, ValidationResult } from './types.js';

declare const require: (path: string) => CountryData;

const LOADERS: Record<string, () => CountryData> = {
${loaders}
};

export const SUPPORTED_COUNTRIES = Object.keys(LOADERS) as readonly string[];

export function ensureCountry(code: string): boolean {
  const cc = code.toUpperCase();
  if (isCountryLoaded(cc)) return true;
  const loader = LOADERS[cc];
  if (!loader) return false;
  registerCountry(loader());
  return true;
}

export function registerAllCountries(): readonly string[] {
  for (const cc of SUPPORTED_COUNTRIES) ensureCountry(cc);
  return SUPPORTED_COUNTRIES;
}

export function validatePostalCode(country: string, raw: string): ValidationResult | undefined {
  if (!country || !ensureCountry(country)) return undefined;
  return packageValidate(country, raw);
}

export function isValidPostalCode(country: string, raw: string): boolean {
  return validatePostalCode(country, raw)?.verdict === 'valid';
}

export function isAcceptablePostalCode(country: string, raw: string): boolean {
  const result = validatePostalCode(country, raw);
  return result === undefined || result.verdict !== 'malformed';
}

export function getCountryFormat(country: string): CountryFormat | undefined {
  if (!country || !ensureCountry(country)) return undefined;
  return packageGetCountryFormat(country);
}

export type { CountryFormat, ValidationResult, ValidationVerdict } from './types.js';
export { UnknownCountryError } from './validator.js';
`;
}

function renderCjs(codes: readonly string[]): string {
  // Hand-rolled CJS with literal `require(...)` calls. Metro's static dep
  // extractor needs to see literal `require(stringLiteral)` to pull the JSON
  // files into the bundle; tsup's `__require` shim hides that pattern.
  const loaders = codes
    .map((cc) => `  ${cc}: () => require('../data/${cc}.json'),`)
    .join('\n');
  return `${HEADER}
'use strict';
Object.defineProperty(exports, '__esModule', { value: true });

const main = require('./index.cjs');

const LOADERS = {
${loaders}
};

const SUPPORTED_COUNTRIES = Object.keys(LOADERS);

function ensureCountry(code) {
  const cc = String(code).toUpperCase();
  if (main.isCountryLoaded(cc)) return true;
  const loader = LOADERS[cc];
  if (!loader) return false;
  main.registerCountry(loader());
  return true;
}

function registerAllCountries() {
  for (const cc of SUPPORTED_COUNTRIES) ensureCountry(cc);
  return SUPPORTED_COUNTRIES;
}

function validatePostalCode(country, raw) {
  if (!country || !ensureCountry(country)) return undefined;
  return main.validatePostalCode(country, raw);
}

function isValidPostalCode(country, raw) {
  const result = validatePostalCode(country, raw);
  return result !== undefined && result.verdict === 'valid';
}

function isAcceptablePostalCode(country, raw) {
  const result = validatePostalCode(country, raw);
  return result === undefined || result.verdict !== 'malformed';
}

function getCountryFormat(country) {
  if (!country || !ensureCountry(country)) return undefined;
  return main.getCountryFormat(country);
}

exports.SUPPORTED_COUNTRIES = SUPPORTED_COUNTRIES;
exports.ensureCountry = ensureCountry;
exports.registerAllCountries = registerAllCountries;
exports.validatePostalCode = validatePostalCode;
exports.isValidPostalCode = isValidPostalCode;
exports.isAcceptablePostalCode = isAcceptablePostalCode;
exports.getCountryFormat = getCountryFormat;
exports.UnknownCountryError = main.UnknownCountryError;
`;
}

function renderMjs(): string {
  // ESM bridge: re-export the CJS API via Node's ESM/CJS interop. Anyone
  // consuming this entry through a static bundler (Metro / webpack) will hit
  // the CJS file via the package.json "require" condition — the .mjs is for
  // Node ESM consumers who imported the entry directly.
  return `${HEADER}
import bundled from './bundled.cjs';
export const {
  SUPPORTED_COUNTRIES,
  ensureCountry,
  registerAllCountries,
  validatePostalCode,
  isValidPostalCode,
  isAcceptablePostalCode,
  getCountryFormat,
  UnknownCountryError,
} = bundled;
export default bundled;
`;
}

function renderDts(): string {
  return `${HEADER}
import type { CountryFormat, ValidationResult } from './index.js';

export declare const SUPPORTED_COUNTRIES: readonly string[];
export declare function ensureCountry(code: string): boolean;
export declare function registerAllCountries(): readonly string[];
export declare function validatePostalCode(country: string, raw: string): ValidationResult | undefined;
/** True iff \`raw\` is a complete, known postal code in the reference dataset. */
export declare function isValidPostalCode(country: string, raw: string): boolean;
/**
 * True iff \`raw\` is structurally well-formed for the country (or the country
 * isn't shipped by this build so no validation is possible). Use this for the
 * "can the user proceed" gate.
 */
export declare function isAcceptablePostalCode(country: string, raw: string): boolean;
/**
 * Structural description of the country's postal codes (length bounds, digit/
 * letter classes). Useful for configuring an input field — max length, keyboard
 * type, auto-capitalize. Returns \`undefined\` when this build doesn't bundle
 * the country.
 */
export declare function getCountryFormat(country: string): CountryFormat | undefined;
export { UnknownCountryError } from './index.js';
export type { CountryFormat, ValidationResult, ValidationVerdict } from './index.js';
`;
}
