// @generated by scripts/build-bundled.ts — DO NOT EDIT.
// Source: data/manifest.json (121 countries).

import { isCountryLoaded, registerCountry } from './registry.js';
import {
  validatePostalCode as packageValidate,
  getCountryFormat as packageGetCountryFormat,
} from './validator.js';
import { regexForCountry as packageRegexForCountry } from './regex.js';
import { normalizePostalCode } from './normalize.js';
import type { CountryData, CountryFormat, ValidationResult } from './types.js';

declare const require: (path: string) => CountryData;

const LOADERS: Record<string, () => CountryData> = {
  AD: () => require('../data/AD.json'),
  AE: () => require('../data/AE.json'),
  AI: () => require('../data/AI.json'),
  AL: () => require('../data/AL.json'),
  AR: () => require('../data/AR.json'),
  AS: () => require('../data/AS.json'),
  AT: () => require('../data/AT.json'),
  AU: () => require('../data/AU.json'),
  AX: () => require('../data/AX.json'),
  AZ: () => require('../data/AZ.json'),
  BD: () => require('../data/BD.json'),
  BE: () => require('../data/BE.json'),
  BG: () => require('../data/BG.json'),
  BM: () => require('../data/BM.json'),
  BR: () => require('../data/BR.json'),
  BY: () => require('../data/BY.json'),
  CA: () => require('../data/CA.json'),
  CC: () => require('../data/CC.json'),
  CH: () => require('../data/CH.json'),
  CL: () => require('../data/CL.json'),
  CN: () => require('../data/CN.json'),
  CO: () => require('../data/CO.json'),
  CR: () => require('../data/CR.json'),
  CX: () => require('../data/CX.json'),
  CY: () => require('../data/CY.json'),
  CZ: () => require('../data/CZ.json'),
  DE: () => require('../data/DE.json'),
  DK: () => require('../data/DK.json'),
  DO: () => require('../data/DO.json'),
  DZ: () => require('../data/DZ.json'),
  EC: () => require('../data/EC.json'),
  EE: () => require('../data/EE.json'),
  ES: () => require('../data/ES.json'),
  FI: () => require('../data/FI.json'),
  FK: () => require('../data/FK.json'),
  FM: () => require('../data/FM.json'),
  FO: () => require('../data/FO.json'),
  FR: () => require('../data/FR.json'),
  GB: () => require('../data/GB.json'),
  GF: () => require('../data/GF.json'),
  GG: () => require('../data/GG.json'),
  GI: () => require('../data/GI.json'),
  GL: () => require('../data/GL.json'),
  GP: () => require('../data/GP.json'),
  GS: () => require('../data/GS.json'),
  GT: () => require('../data/GT.json'),
  GU: () => require('../data/GU.json'),
  HK: () => require('../data/HK.json'),
  HM: () => require('../data/HM.json'),
  HN: () => require('../data/HN.json'),
  HR: () => require('../data/HR.json'),
  HT: () => require('../data/HT.json'),
  HU: () => require('../data/HU.json'),
  ID: () => require('../data/ID.json'),
  IE: () => require('../data/IE.json'),
  IM: () => require('../data/IM.json'),
  IN: () => require('../data/IN.json'),
  IO: () => require('../data/IO.json'),
  IS: () => require('../data/IS.json'),
  IT: () => require('../data/IT.json'),
  JE: () => require('../data/JE.json'),
  JP: () => require('../data/JP.json'),
  KE: () => require('../data/KE.json'),
  KR: () => require('../data/KR.json'),
  LI: () => require('../data/LI.json'),
  LK: () => require('../data/LK.json'),
  LT: () => require('../data/LT.json'),
  LU: () => require('../data/LU.json'),
  LV: () => require('../data/LV.json'),
  MA: () => require('../data/MA.json'),
  MC: () => require('../data/MC.json'),
  MD: () => require('../data/MD.json'),
  MH: () => require('../data/MH.json'),
  MK: () => require('../data/MK.json'),
  MO: () => require('../data/MO.json'),
  MP: () => require('../data/MP.json'),
  MQ: () => require('../data/MQ.json'),
  MT: () => require('../data/MT.json'),
  MW: () => require('../data/MW.json'),
  MX: () => require('../data/MX.json'),
  MY: () => require('../data/MY.json'),
  NC: () => require('../data/NC.json'),
  NF: () => require('../data/NF.json'),
  NL: () => require('../data/NL.json'),
  NO: () => require('../data/NO.json'),
  NR: () => require('../data/NR.json'),
  NU: () => require('../data/NU.json'),
  NZ: () => require('../data/NZ.json'),
  PA: () => require('../data/PA.json'),
  PE: () => require('../data/PE.json'),
  PF: () => require('../data/PF.json'),
  PH: () => require('../data/PH.json'),
  PK: () => require('../data/PK.json'),
  PL: () => require('../data/PL.json'),
  PM: () => require('../data/PM.json'),
  PN: () => require('../data/PN.json'),
  PR: () => require('../data/PR.json'),
  PT: () => require('../data/PT.json'),
  PW: () => require('../data/PW.json'),
  RE: () => require('../data/RE.json'),
  RO: () => require('../data/RO.json'),
  RS: () => require('../data/RS.json'),
  RU: () => require('../data/RU.json'),
  SE: () => require('../data/SE.json'),
  SG: () => require('../data/SG.json'),
  SI: () => require('../data/SI.json'),
  SJ: () => require('../data/SJ.json'),
  SK: () => require('../data/SK.json'),
  SM: () => require('../data/SM.json'),
  TC: () => require('../data/TC.json'),
  TH: () => require('../data/TH.json'),
  TR: () => require('../data/TR.json'),
  UA: () => require('../data/UA.json'),
  US: () => require('../data/US.json'),
  UY: () => require('../data/UY.json'),
  VA: () => require('../data/VA.json'),
  VI: () => require('../data/VI.json'),
  WF: () => require('../data/WF.json'),
  WS: () => require('../data/WS.json'),
  YT: () => require('../data/YT.json'),
  ZA: () => require('../data/ZA.json'),
};

export const SUPPORTED_COUNTRIES = Object.keys(LOADERS) as readonly string[];

export function ensureCountry(code: string): boolean {
  const cc = code.toUpperCase();
  if (isCountryLoaded(cc)) return true;
  const loader = LOADERS[cc];
  if (!loader) return false;
  registerCountry(loader());
  return true;
}

export function registerAllCountries(): readonly string[] {
  for (const cc of SUPPORTED_COUNTRIES) ensureCountry(cc);
  return SUPPORTED_COUNTRIES;
}

export function validatePostalCode(country: string, raw: string): ValidationResult | undefined {
  if (!country || !ensureCountry(country)) return undefined;
  return packageValidate(country, raw);
}

export function isValidPostalCode(country: string, raw: string): boolean {
  return validatePostalCode(country, raw)?.verdict === 'valid';
}

export function isAcceptablePostalCode(country: string, raw: string): boolean {
  const result = validatePostalCode(country, raw);
  return result === undefined || result.verdict !== 'malformed';
}

export function getCountryFormat(country: string): CountryFormat | undefined {
  if (!country || !ensureCountry(country)) return undefined;
  return packageGetCountryFormat(country);
}

export function regexForCountry(country: string): RegExp | undefined {
  if (!country || !ensureCountry(country)) return undefined;
  return packageRegexForCountry(country);
}

export { normalizePostalCode };

export type { CountryFormat, ValidationResult, ValidationVerdict } from './types.js';
export { UnknownCountryError } from './validator.js';
